'use client'
import "./globals.css";
import { Inter } from "next/font/google";
import ReactQuery from "@/components/ReactQuery";
import { RecoilRoot } from "recoil";
import Header from "@/components/main/header";
import LandingHeader from "@/components/main/landingHeader";

import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Gaebokchi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  // 현재 url : string
  let curURL = usePathname()

  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRoot>
          <ReactQuery>
            {/* 현재 url에 따라 다르게 보이는 헤더 */}
            {curURL == '/' ? <LandingHeader /> : curURL == '/login' ? null : <Header />}
            {children}
          </ReactQuery>
        </RecoilRoot>
      </body>
    </html>
  );
}
